### ISSUE TITLE
system-id is getting clobbered on restart

### ISSUE THREAD

**Issue by iherdgoats** [canonical/microovn#10]
The snap doesn't include uuidgen so the system-id is getting cleared on service restarts. Though ultimately it probably makes sense to figure out how to disable the reinitialisation behavior so that we can retain the hostname based id.

**Comment by stgraber** [comment]
Oh, that should be an easy fix, I see that `switch.start` incorrectly calls ovs-ctl with system-id=random when that should just be using the hostname, same as we set in OVN through the Go logic.
